name: Github Readme YT Cards
on: 
  schedule:

    - cron: "0 * * * *"
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubunto-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with: 
          channel_id: UCf4V-LYQTD1KFwYW8MNcp6g
